export const HEALTH_INSURANCE = 362.34;
export const SOCIAL_CONTRIBUTION_LOWERED = 227.69;
export const SOCIAL_CONTRIBUTION = 915.46;
export const OPTIONAL_SICKNESS_INSURANCE_LOWERED = 19.11;
export const OPTIONAL_SICKNESS_INSURANCE = 76.84;
export const ADDITIONAL_INSURANCE_COST = 76.84;

export const LINEAR_TAX_RATE = 0.19;
export const PROGRESSIVE_TAX_RATE_BASE = 0.17;
export const PROGRESSIVE_TAX_RATE_OVER_THRESHOLD = 0.32;
export const PROGRESSIVE_TAX_THRESHOLD = 85528;

export const VAT = 0.23;
export const GROSS_BASE = 1 + VAT;

export const CAR_EXPENSE_VAT_RATE = 0.5;
export const CAR_EXPENSE_COST_RATE = 0.75;
